### ISSUE TITLE
Node process is not attached.

### ISSUE THREAD

**Issue by yograf** [GoogleChromeLabs/ndb#107]
Node processes pane just empty with "No running nodes".

### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.19
* Platform / OS version: Ubuntu 16.04
* Node.js version:10.7.0

**What steps will reproduce the problem?**
Start ndb with the node js script
_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
To attach to the node process

**What happens instead?**

**Comment by ak239** [comment]
Thanks for your report!
Could you provide more details about your script? Does ndb work for other scripts? Is it possible to evaluate any expression from ndb console?

**Comment by ak239** [comment]
I will reopen this one as soon as we will get more feedback. Unfortunately we do not have enough information to investigate this problem. 😞

**Comment by davewasmer** [comment]
I'm seeing this as well. I've tried launching ndb from a local install, as well as globally, with no difference. I can't get it to connect to anything.

It launches the devtools panel, and after a delay, I see the local directory appear in the Filesystem tab. But nothing appears to be running. The console output is entirely empty, and the dropdown that normally lets you pick which frame's output to view in the console pane is just empty:

![image](https://user-images.githubusercontent.com/707213/49107925-25c27900-f244-11e8-9e03-95babf00137e.png)

The terminal panel just prints out a couple of node inspector URLs initially. If I Ctrl-C, it seems to kill whatever was running there, but then trying to launch a node process from there also does nothing (besides just print out those debug URLs and hang as well):

![image](https://user-images.githubusercontent.com/707213/49108010-55718100-f244-11e8-9d19-9d3be4c836d4.png)

The NPM Scripts pane is correctly populating as well, but clicking on the "Start" button on any of the tasks does nothing.

**Comment by davewasmer** [comment]
macOS 10.14.1
ndb 1.0.35

**Comment by davewasmer** [comment]
I dunno if this is relevant, but I just noticed a couple dozen node processes sitting around, despite me not running anything currently. It's possible that my main app's nodemon setup is botched and is leaving around server processes on restarts, or perhaps it's from ndb. Not sure, but figured I'd let you know just in case.

**Comment by davewasmer** [comment]
That seems to do it. I can now start the node process and it attaches correctly.

FWIW though - I can't seem to use `ndb` in anything other than a direct invocation of node, i.e. `ndb node ...`. I've tried `ndb nodemon ...` and `ndb yarn ...` and it fails - it seems like it captures any command line args and passes them straight to node, rather than preserving them with the original binary invocation.

Happy to file a separate issue for that if you'd like.
