### ISSUE TITLE
Failed to download Chromium r575458!

### ISSUE THREAD

**Issue by qiangf811** [GoogleChromeLabs/ndb#108]
sudo npm install ndb -g,
but it failed:
node-v:v10.8.0
platform:MacOs
![image](https://user-images.githubusercontent.com/18138724/43705046-1777ecbc-9994-11e8-868d-f252b2e77a05.png)

**Comment by ak239** [comment]
Could you check from your browser or from terminal (using wget or curl) that this [link](https://storage.googleapis.com/chromium-browser-snapshots/Mac/575458/chrome-mac.zip) is available from your machine?

**Comment by ak239** [comment]
Most likely this link is unavailable from your network. It may have different reasons, e.g. your system administrator may have white-list of available external urls or you need to use proxy to access some remote resources. In first case you can ask your system administrator about white-listing chromium snapshots domain. In second case you can specify proxy as HTTP_PROXY=... environment variable.

**Comment by qiangf811** [comment]
The network is ok. I already have access to 'google.com'，but it failed at last step to install **puppeteer**,and then ... it happend

**Comment by qiangf811** [comment]
finally,i installed it.thank you very much.
