### ISSUE TITLE
Question: is there any way to stop a running program?

### ISSUE THREAD

**Issue by transitive-bullshit** [GoogleChromeLabs/ndb#113]
Oftentimes, I want to stop the node process I'm debuggiing, change something, and restart it. Currently, the only way to do so that I can find is by deactivating breakpoints, pressing continue, waiting for the program to end, and then re-enabling breakpoints, making my change, and starting the program again.

This is pretty common IDE functionality; am I missing this or does it need to be added?

* ndb version: v1.0.20
* Platform / OS version: Mac OS High Sierra
* Node.js version: 10.3.0

Thanks!!

**Comment by ak239** [comment]
There are two features that may help:
- there is kill button (square one) next to each process in Node Processes list,
- our you can press `Cmd + R` on Mac or `Ctrl + R` on Linux / Windows to restart configuration that was started last.

Will these options work for you?

<img src=https://user-images.githubusercontent.com/426418/43869680-9ba31076-9b28-11e8-993f-fcfaad8437c6.png width=400px/>

**Comment by transitive-bullshit** [comment]
Awesome, thanks for the quick response @ak239.

These two are perfect :) They are a bit hidden, though. Perhaps in the future they can be made more discoverable in the UI?

Thanks, again!

**Comment by ak239** [comment]
Yes, we definitely need nice place for restart and kill button. I will experiment with them. Thanks for your feedback!
