### ISSUE TITLE
feature request: one window to rule them all

### ISSUE THREAD

**Issue by selfagency** [GoogleChromeLabs/ndb#115]
love ndb!

however, if you're developing with a tool like nodemon and you have it watching file changes, every time you make and save an edit, the process is restarted, and the ndb window closes and then reopens. as you might imagine, this can be very annoying, especially if you like to keep your workspace organized with a split screen, for example. 

ndb should have an optional parent window that maintains its size and position where instances of devtools open and close in tabs as children of that parent window. 

you could launch a parent window with one command, like `ndb --new-parent="myProject"` and then assign sessions to the parent with a common session identifier, like `ndb app.js --child-of="myProject"`. the parent window would remain open until it's manually closed or a kill signal is sent from the terminal.

i hope you'll consider this feature. thanks for the great tool!

**Comment by ak239** [comment]
I believe that you use ndb in some way like following:
```bash
nodemon ndb index.js
```
Could you try to a little changed command where ndb is first and nodemon is second? Would this setup work for you? You can try to edit files right inside ndb and nodemon should properly restart your script without restarting ndb.
```bash
ndb nodemon index.js
```

**Comment by selfagency** [comment]
unfortunately, there's one little problem there, which is that the main process being observed and profiled then becomes nodemon and not my application, which does not run with nodemon in production.

**Comment by ak239** [comment]
I believe that nodemon should not affect the running process, it detects source changes and restarts process, so it should not affect the performance of your app. From the ndb point of view, there is no difference in child process inspection and main process inspection.
If you need to request pause within your running app, you can select app process in Node processes sidebar and click the Pause button. If you would like to profile code, you can go to the Profiler tab and choose your running app process to profile it.

As the alternative, you can go to Terminal tab (which is next to console in the drawer) and run `nodemon index.js` from there.

Or I miss something, feel free to explain :)

<img src=https://user-images.githubusercontent.com/426418/43915665-4553bc96-9bc0-11e8-98b1-66a7dc3f5088.png width=400px>

**Comment by ak239** [comment]
Another alternative you can run your app without nodemon at all and restart it using `Ctrl+R` or `Cmd+R` shortcut manually, but it definitely sounds like less user friendly solution then nodemon.

**Comment by ak239** [comment]
This one and #60 have the same root. Please follow that issue and thanks for your report!
