### ISSUE TITLE
Memory Profiler not working in recent releases

### ISSUE THREAD

**Issue by Jacob-Noah** [GoogleChromeLabs/ndb#116]
The memory profiler is not working in builds v1.0.22 and v1.0.21, however I downgraded to v1.0.20 and the expected result comes out just fine.

This is the first issue I've posted on GitHub but I'm a big fan of this project so I'd like to contribute. I'm not sure if it's useful, but I'm searching far and wide for a memory leak. My application relies heavily on the event emitter and database connectivity, but this is not a blackbox issue.

**Environment:**

* ndb version: v1.0.22 (latest release) or v1.0.21
* Platform / OS version: Microsoft Windows 10 v1803 OS Build 17134.165
* Node.js version: v10.8.0

**To reproduce:**

1. Run app via `ndb node app.js`
2. Visit the memory profiler and start an allocation instrumentation on timeline profile, end it after a few seconds.

**Expected result:**
A snapshot will build and finalize.

**Result:**
The snapshot hangs at "Loading..."

**Comment by ak239** [comment]
ndb@1.0.23 just published and should contain fix for this issue, thanks for your report!

**Comment by Jacob-Noah** [comment]
Many thanks to you as well! 😄
