### ISSUE TITLE
How to change font size in devtools in ndb?

### ISSUE THREAD

**Issue by vadzim-revolist** [GoogleChromeLabs/ndb#130]
Hi!

Not sure this is the right place for such questions,
but is there a way to enlarge font size in devtools in ndb?
I can do that easily with Ctrl+/- in chrome, but not in ndb.

I didn't find an option for that in `README` and in `Settings`.

**Comment by ak239** [comment]
Please try `Ctrl+Shift++/-`. It should work. We definitely should mention it in `README`.

**Comment by vadzim-revolist** [comment]
Yes, that works.
Thank you!
