### ISSUE TITLE
ndb not pausing on "debugger" statements.

### ISSUE THREAD

**Issue by trusktr** [GoogleChromeLabs/ndb#133]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.24
* Platform / OS version: macOS 10.13.4
* Node.js version: 10.9.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Put a `debugger` line in a file.
2. Run the app with `ndb`

**What is the expected result?**

I'd like it to pause on `debugger` lines.

**What happens instead?**

It never pauses, and it gets to other lines that are later on where my error is happening, so I can't step through it.

---

I'm doing something like `ndb npm start` which runs `./node_modules/.bin/next src` which then run Webpack.

Eventually, I see the error in the ndb devtools console. However, it never stops on my debuggers. If I enable the auto-pause button,

![screen shot 2018-09-04 at 12 32 59 pm](https://user-images.githubusercontent.com/297678/45053393-b2430e00-b03e-11e8-93ed-ca1f01296f41.png)

it still never pauses before the error.

---

How do I make it stop on `debugger` statements? How do I make it pause before errors?

**Comment by trusktr** [comment]
Also, once the error happens (which happens quickly), I can not explore any objects I logged to the console. When I click the dropdown icons next to the object in the console output, it shows nothing:

![screen shot 2018-09-04 at 12 41 51 pm](https://user-images.githubusercontent.com/297678/45053809-f7b40b00-b03f-11e8-933f-b9d78d6970df.png)

It shows nothing, and the next line is `<<<<` which is just a `console.log('<<<<')`, and there's nothing in the middle between the expanded object and the `<<<<`.

**Comment by trusktr** [comment]
Without being able to pause or inspect objects, there's not much I can really do with ndb. Is this a bug? Or am I missing something?

**Comment by ak239** [comment]
I believe that the issue here is auto blackboxing. ndb tries to blackbox everything except files from your project by default. Could you try to go to settings and disable - "Blackbox anything outside working directory"?

**Comment by trusktr** [comment]
Yep, that was it. Thanks!
