### ISSUE TITLE
executablePath is not in the launcher options list

### ISSUE THREAD

**Issue by andrewmiller1** [GoogleChromeLabs/ndb#134]
Please add. Example:

```js
const browser = await puppeteer.launch({
  appMode: true,
  dumpio: true,
  userDataDir,
  args: [
    '--app=data:text/html,<style>html{background:#242424;}</style>',
    '--enable-features=NetworkService',
    '--no-sandbox',
    '-disable-web-security'
  ],
  devtools: options.debugFrontend,
  executablePath: '/usr/bin/chrome'
});
```
Works on Chromium 71.0.3543.0 custom

Might be a bit more involved since you'd want to parameters to it. Let me know if you want some help

**Comment by ak239** [comment]
I am going to add detecting installed Chrome instead of downloading one soon.

**Comment by mlucool** [comment]
Puppeteer now allows for the executable path in the environment via `PUPPETEER_EXECUTABLE_PATH`. Can we make it possible to use this?

See: https://github.com/GoogleChrome/puppeteer/releases/tag/v1.8.0

**Comment by ak239** [comment]
please check 1.0.28. ndb was migrated to carlo and now will try to locate local chrome first before downloading chromium.
thanks for your request!
