### ISSUE TITLE
Console.context is not a function

### ISSUE THREAD

**Issue by soundstep** [GoogleChromeLabs/ndb#135]
ndb: v1.0.24
OS: Max Sierra 10.12.6
Node: v8.3.0

1. launch a small script that start an express server: `ndb index.js`
2. go to the console tab

**What is the expected result?**

No error in the console

**What happens instead?**

Devtools seems to struggle, it throws `console.context` errors, about 20 times.
After this it works correctly.

<img width="1290" alt="screen shot 2018-09-06 at 13 16 53" src="https://user-images.githubusercontent.com/133293/45157084-fe758600-b1d7-11e8-8c77-f24a07d367ec.png">

**Comment by ak239** [comment]
Could you update Node to latest 8.x release in your environment? This issue should be fixed in node v8.11.3.
Thanks for your report!

**Comment by ak239** [comment]
Should be fixed in v1.0.26. Please update your ndb.

**Comment by StreetStrider** [comment]
What is the `console.context`? @ak239
