### ISSUE TITLE
How to debug a remote node service ? 

### ISSUE THREAD

**Issue by Peter-WF** [GoogleChromeLabs/ndb#137]
Node with —inspect can be directly connected to normal chrome browser. It can create a connection between local chrome browser and remote node service.

https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by dcorb** [comment]
Could help? https://github.com/GoogleChromeLabs/ndb/issues/60#issuecomment-421413833

**Comment by moltar** [comment]
I am interested in this question too.

My use case is actually debugging a remote process (it's on Heroku). The Heroku instance exposes a port 9229 via port forwarding to my local machine. So the port is available on `127.0.0.1:9229`. Chrome recognizes this via `chrome://inspect`, but I can't figure out how to get `ndb` to see it.

**Comment by Peter-WF** [comment]
@dcorb Thanks for your suggestion, but `ndb-inspect` still doesn't seem to help me build a local to remote connection that can be used for remote debugging.

**Comment by ak239** [comment]
We need to add remote debugging capabilities to `ndb`.
https://github.com/GoogleChromeLabs/ndb/issues/48 is very close feature request.
