### ISSUE TITLE
Full screen on OS X freezes ndb

### ISSUE THREAD

**Issue by jeremyckahn** [GoogleChromeLabs/ndb#14]
This is a very exciting and useful project, thank you for sharing this with the community!

### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.3
* Platform / OS version: OS X 10.13.5
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

Launch ndb with `ndb .` in any JS project, and then fullscreen the app via the green OS button in the upper-left of the app frame. Give it a few seconds and observe the endless OS X beachball until you ctrl+c the CLI command that launched it.

_Please include code that reproduces the issue._

1. `ndb .`

**What is the expected result?**

The app does not freeze.

**What happens instead?**

The app freezes.

**Comment by ak239** [comment]
Thanks for you bug report!
I tracked it down to `pipe: true` flag that we pass to pptr implicitly. Most likely it is something about Chromium with `--remote-debugging-pipe` flag behavior on Mac. I will continue debugging this issue.

**Comment by transitive-bullshit** [comment]
Just adding that I have _not_ run into this issue on a similar setup:

ndb: 1.0.4
platform: macOS 10.13.6
node.js: 10.3.0

Hope it helps w/ debugging.

**Comment by jeremyckahn** [comment]
ndb@1.0.5 is working much better for me. Thank you for the quick fix!
