### ISSUE TITLE
cannot use export and import

### ISSUE THREAD

**Issue by FridaCai** [GoogleChromeLabs/ndb#142]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.24
* Platform / OS version: Window7
* Node.js version: v8.11.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**
cannot use 'export' and 'import'.
Uncaught SyntaxError: Unexpected token export

**Comment by ak239** [comment]
Could you provide source of script? 
Thanks for you report.

**Comment by ak239** [comment]
You may try to use `--experimental-modules flag`, feel free to comment this issue with more details.

**Comment by FridaCai** [comment]
![untitled picture](https://user-images.githubusercontent.com/12479174/45729889-4eedda00-bc01-11e8-896b-ea96cd7a8e8f.png)

**Comment by FridaCai** [comment]
Thanks for your reply. 
I have tried --experimental-modules flag, it does not work.
It looks like reserved word 'import' is not supported.

**Comment by ak239** [comment]
In node to use ESM modules, your module file should have .mjs extension. So please rename your script to .mjs and run it with --experimental-modules flag.
