### ISSUE TITLE
Pausing on save

### ISSUE THREAD

**Issue by andrewmiller1** [GoogleChromeLabs/ndb#150]
Trying to watch variables as I code. Is there a way to have ndb to restart the process on file save, without it pausing at the beginning of the script?

**Comment by ak239** [comment]
Could you share more details? Do you edit code on pause? Do you use nodemon? Could you uncheck `Pause at start` checkbox and confirm that it does not help?

Thanks for your reprort!

![image](https://user-images.githubusercontent.com/426418/45957231-6514e500-bfc9-11e8-8192-d4cd979d2dab.png)

**Comment by andrewmiller1** [comment]
Firstly, I'd like to ask: The separate but ideal case live programming. That is, as I type (rather than on save), expressions in the "Watch" area and the programming environment in the "Scope" area update. I would only need access to the function that evaluates the expressions. I can use watchman (I do not use watchman in this issue). Is this kind of debug functionality already supported or is there already an API function I can call to update the evaluations of a specific process in the "Watch" and "Scope" areas at will?

Back to my original issue.

Note that, although I upgraded ndb from 1.0.25 to 1.0.26, my original situation hasn't changed. But my understanding of it has. The issue is redefined below.

---

> Could you share more details?

### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.26
* Platform / OS version: Linux pop-os 4.19.0-041900rc2-generic, Distributor ID: Ubuntu, Description: Pop!_OS 18.04 LTS, Release: 18.04, Codename: bionic, /etc/debian_version: buster/sid
* Node.js version: v10.10.0

Additional info:

* My system has no global ndb.
* My node is managed by nvm.
* ndb is locally installed in a no-frills project with `npm --save-dev install ndb`.
* `/path/to/project/node_modules/.bin` is in `PATH`

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

<details><summary>./index.js</summary>

```js
const myVal = "I'm a value";
debugger;
```

</details><br>

1. Bash: `ndb index.js`. ndb pops up with main: `index.js` included in the "NPM Scripts" area. Click on main's "Run" button. ndb pausing on `debugger;`. In the "Scope" area, I see the environment structure with values. `myVal: "I'm a value"` is there.
2. ndb: In the ndb editor, change myVal to `"I'm a changed value"`.
3. ndb: Save the file via `ctrl+s`. ndb pausing on line 1. In the "Scope" area, I see the environment structure with values. `myVal: undefined` is there.
4. ndb: In the ndb editor, change myVal to `"I'm a newly changed value again"`.
5. ndb: Save the file via `ctrl+s`. ndb pausing on `debugger;`. In the "Scope" area, I see the environment structure with values. `"I'm a newly changed value again"` is there.

**What is the expected result?**

ndb reruns the process on save, pausing on `debugger;` every time. The Scope area is updated with the new values.


**What happens instead?**

ndb reruns the process on save, pausing on `debugger;` every *other* time. The Scope area is updated with the new values as a result every *other* time.


---

> Do you edit code on pause?

Yes.


---

> Do you use nodemon?

No.


---

> Could you uncheck Pause at start checkbox and confirm that it does not help?

It was already unchecked.

Additional info:

For science I now checked it. Ran the above steps. The inverse happens. The first time I save, the process is rerun, pausing on `debugger;`. Making further changes and saves still results in the same issue. It alternates between pausing on line 1 and pausing on `debugger;`.


---

I can get you any logs you need from any command if it could help. Just let me know what will give you more to look at and I'll have it on its way to you

**Comment by aliaa159** [comment]
Now working !

**Comment by ak239** [comment]
`ndb` by default tries to use builtin V8 liveedit feature to restart current stack trace with updated code without restarting process. So in this case execution is paused on first line every time because V8 restarts top frame with new code.
Process always can be restarted by using `Cmd + R` on Mac or `Ctrl + R` on Linux and Windows.
