### ISSUE TITLE
never had 'debugger attached' when running ndb npm test

### ISSUE THREAD

**Issue by edgecase101** [GoogleChromeLabs/ndb#153]
I just installed ndb to my Mac. However, running 'ndb npm test' **hangs** after these 2 lines --

Debugger listening on ws://127.0.0.1:63321/c5ac1f95-aa18-4330-a549-2c35483962fb
For help see https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:63321/045e20d7-0a7b-4ffd-84b6-9eb967011dcd
For help see https://nodejs.org/en/docs/inspector

Also on the ndb console, I never see 'welcom to ndb REPL'.

Please help!
<img width="1318" alt="screen shot 2018-09-27 at 4 13 52 pm" src="https://user-images.githubusercontent.com/4895061/46179592-db874080-c270-11e8-8b2c-4b5e8e65ea40.png">

### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.26
* Platform / OS version: 10.13.6
* Node.js version: 10.10.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by ak239** [comment]
Could you try to update node to latest version (10.11.0)?

**Comment by ak239** [comment]
I will reopen this one as soon as you provide more details, unfortunately I can not reproduce this problem.
