### ISSUE TITLE
Question: should it work for WSL?

### ISSUE THREAD

**Issue by daKmoR** [GoogleChromeLabs/ndb#154]
### Steps to reproduce

**Tell us about your environment:**
$ ndb --version
v1.0.26

$ npx https://gist.github.com/daKmoR/b509ed34576a488ea79d3ac66ccab74e
npx: installed 1 in 5.344s
$ node --version
v10.9.0

$ npm --version
6.4.1

$ cat /proc/version:
It is a WSL (Windows Linux Subystem)
Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #285-Microsoft Thu Aug 30 17:31:00 PST 2018

$ lsb_release -a:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**What steps will reproduce the problem?**

```
$ ndb .
// alternative 
$ ndb index.js
```

```js
// index.js
console.log('foo');
debugger;
console.log('bar');
```

**What is the expected result?**
Opens ndb

**What happens instead?**
Does nothing.

I tried setting 
```
export PUPPETEER_EXECUTABLE_PATH=/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe
```

to use installed chrome instead of puppeteer (as I saw there might be problems with WSL) => still didn't change a thing

**Comment by ak239** [comment]
Unfortunately it is known problem with puppeteer. Please track https://github.com/GoogleChromeLabs/ndb/issues/33 for updates and thanks for your report!
