### ISSUE TITLE
ndb command must be terminated manually after closing ndb window

### ISSUE THREAD

**Issue by diminutivesloop** [GoogleChromeLabs/ndb#155]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.26
* Platform / OS version: Windows 7
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

1. From command prompt run `ndb`.
2. Close main ndb window.

**What is the expected result?**
The `ndb` command should exit and return to the command prompt.

**What happens instead?**
The `ndb` command is still running and must be manually terminated either by closing the command prompt window or by using ctrl+c.

**Comment by ak239** [comment]
Could you please check 1.0.28? It should be fixed there.

**Comment by diminutivesloop** [comment]
Ok. I checked and it appears to have been fixed.

**Comment by ak239** [comment]
Thanks!
