### ISSUE TITLE
Flame chart

### ISSUE THREAD

**Issue by amejiarosario** [GoogleChromeLabs/ndb#159]
How do I generate a flame chart?

e.g.
![image](https://user-images.githubusercontent.com/418605/47933182-3b918800-deaa-11e8-8bf7-845a6643e1a0.png)

**Comment by the-kozy** [comment]
You can run your script with ndb and use "Start recording" button to record profile.
![screenshot from 2018-11-02 14-54-50](https://user-images.githubusercontent.com/426418/47942469-531f3f80-deaf-11e8-9491-d2330140b572.png)

**Comment by ak239** [comment]
I will close this issue for now, feel free to comment if you have other feature request or you would like to have better timeline support.
