### ISSUE TITLE
enhancement: add option to NOT attach to subprocesses

### ISSUE THREAD

**Issue by boneskull** [GoogleChromeLabs/ndb#161]
Hi,

I'm trying to debug Mocha's test suite with ndb.

As part of its test suite, it spawns subprocesses which run the `mocha` executable using various options and against various fixtures.

This gets pretty ugly since the output of all subprocesses is dumped into ndb's console.  The test suites *do not* display the subprocess output; it's just stuffed into a buffer where we can make assertions against it.

Likewise, profiling can get messy.

What I'd like is the ability to tell ndb "don't debug subprocesses if the script is *X*".  Maybe that's a regexp or a path to a `.js` file...

Thanks, and great work on ndb.  Glad Mocha's found some use here!

**Comment by ak239** [comment]
Thanks for your feature request!
We would like to redo our blackboxing story and this request will be part of it. ndb will need to connect to child process to get main script name but we can disconnect as soon as we detect that this process should be blackboxed.
Thanks for the mocha!

**Comment by boneskull** [comment]
Thanks for the quick response.  Any way I can help?
