### ISSUE TITLE
doesn't start on files w/o js ext on Windows

### ISSUE THREAD

**Issue by zstauber** [GoogleChromeLabs/ndb#164]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.26 (Chromium r579032)
* Platform / OS version: Windows 10 Pro 64-bit
* Node.js version: 10.1.0

**What steps will reproduce the problem?**
It seems as if it works perfectly on MacOS X, but under Windows it will not run on a file that doesn't have a .js extension.  The examples given by the developers work, such as `ndb server.js`.

However, if you have an express project built whose entry point is ./bin/www, and you type `ndb ./bin/www`, it will open ndb but not start your app.

If you rename ./bin/www to ./bin/www.js and run `ndb ./bin/www.js` it will work.

Similarly, if you have an npm start script in package.json that of
`"scripts": {
    "start": "node ./bin/www",
}`

and if nodemon is installed locally you can run `ndb node_modules/nodemon/bin/nodemon.js`, and it works because this ends with a .js extension and nodemon will run your start script.

But if you have nodemon installed globally, running `ndb nodemon` will not work because it doesn't end in .js.

Again, this is only a Windows issue.  It seems to all run without .js extensions under MacOS X.

**Comment by thomasrdennis1** [comment]
**Encountering Same Issue Different Operating System**

**Tell us about your environment:**
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Version of ndb running: v1.0.42
Node v10.4.1

**Steps to Reproduce:**
Able to successfully run on non express node apps. When trying to execute ndb on express apps that use .bin/www or "scripts": { "start": "node ./bin/www", } as an entry point - the ndb will initialize with no file structure and not start the app. Unable to implement the ".js" workaround outlined in solution for windows.

**Comment by zstauber** [comment]
Yeah, I just tried it on Win10 x64 again with v1.0.42 and still experiencing the issue.  Still able to implement the workaround by referencing everything through ".js" files.  We haven't lost any ground!

**Comment by ak239** [comment]
As possible another workaround you can use explicitly specify `node`: `ndb node ./bin/www`, if this command listed in `package.json` you can use `ndb npm run start` but it looks like a bug with normal express setup - I will take a look.

**Comment by ak239** [comment]
`ndb npm run start` should work just fine with `1.1.1`. Feel free to comment if mentioned workarounds in my previous comment do not work for you.

**Comment by zstauber** [comment]
Excellent!  It works perfectly now, `ndb npm run start` or any other standard ndb command.  Thank you for fixing ndb!
