### ISSUE TITLE
process.stdout and process.stderr could not print to NDB-Console

### ISSUE THREAD

**Issue by Gaubee** [GoogleChromeLabs/ndb#168]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.26
* Platform / OS version: Win10
* Node.js version: v10.12.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. process.stdout.write('stdout')
2. process.stderr.write('stderr')

**What is the expected result?**

NDB-Console should has something print.

**What happens instead?**

but only in Terminal could see some logs.
NDB-Console only print the `process.stderr.write` return is true.

**Comment by ak239** [comment]
Terminal output is available in `terminal` starting `ndb@1.1.0`, press `Esc` to show `Console` drawer and select `Terminal` there.
![image](https://user-images.githubusercontent.com/426418/60833686-a6027280-a173-11e9-9aaf-3ddb41a43e6f.png)
