### ISSUE TITLE
xau

### ISSUE THREAD

**Issue by jmurretxactly** [GoogleChromeLabs/ndb#169]
### Steps to reproduce

**Tell us about your environment:**

* ndb version:
* Platform / OS version:
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by ak239** [comment]
Cool!

**Comment by jmurretxactly** [comment]
apologies.  I have no idea how this got created.

**Comment by jmurretxactly** [comment]
awesome tool btw.  it solved our Jest testing troubles.
