### ISSUE TITLE
add support for standard CLI flags --version and --help

### ISSUE THREAD

**Issue by transitive-bullshit** [GoogleChromeLabs/ndb#17]
### Steps to reproduce

`ndb --version` or `ndb --help`

**Tell us about your environment:**

* ndb version: 1.0.4
* Platform / OS version: mac OS 10.13.6
* Node.js version: 10.3.0

**What is the expected result?**

The ndb CLI should respond to these standard flags by writing to stdout promptly and exit, without opening a Chromium window.

I noticed this when I went to check which version of `ndb` I had installed assuming that `ndb --version` would print out `1.0.4` and exit.

**What happens instead?**

For `ndb --version`, ndb chromium window opens and my node version is printed to the console as well as ndb's normal debugging info.

```
$ ndb --version
v10.3.0
Debugger listening on ws://127.0.0.1:60728/e6cddc0a-85a3-4496-9a24-9d7fddebbc5b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

For `ndb --help`, ndb chromium window opens and the node --help output is printed to the console as well as ndb's normal debugging info.

```
$ ndb --help
Usage: node [options] [ -e script | script.js | - ] [arguments]
       node inspect script.js [arguments]

Options:
  -                          script read from stdin (default; 
                             interactive mode if a tty)
  --                         indicate the end of node options
  --abort-on-uncaught-exception
                             aborting instead of exiting causes a
                             core file to be generated for analysis
  --experimental-modules     experimental ES Module support
                             and caching modules
...
... (redacted)
...
Debugger listening on ws://127.0.0.1:60728/e6cddc0a-85a3-4496-9a24-9d7fddebbc5b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

**Comment by ak239** [comment]
New ndb version (1.0.11) with fix was published to npm. Thanks for your report!
Only -v, --version and --help as first argument are supported.

**Comment by transitive-bullshit** [comment]
Thanks @ak239 -- keep up the great work!
