### ISSUE TITLE
Break out ndb-inspect as a npm package

### ISSUE THREAD

**Issue by johnjbarton** [GoogleChromeLabs/ndb#170]
The current repo has an embedded npm package `ndb-inspect`.   Evidently the only source for this package is here inside of this project.  This awkward arrangement confuses the folks who review our use of npm modules.

I think the system would be clearer if we went one of two directions:
1.  spin out ndb-inspect as its own project. 
2. remove the npm trappings and just load the js where needed.

Would a Pull Request along one of these lines be considered?

**Comment by ak239** [comment]
If I copy `preload.js` file to lib/ and will use it from there and publish ndb without ndb-inspect folder, will it work?

**Comment by johnjbarton** [comment]
If I understand your goal -- to provide a command line feature triggering inspect or brk -- then I think you can move `ndb-inspect/brk` `ndb-inspect/inspect` to the root of this project, then move `preload.js` to say `/lib`.  Adjust the `require(./preload.js)` to `require(./lib/preload.js)`.  Then the feature would be `-r ndb/brk` and -r `ndb/inspect`.

**Comment by ak239** [comment]
Intention behind ndb-inspect was to provide a tool that might be used as dev dependency without forcing users to download full chromium. As soon as ndb is migrated to carlo, we won't need to depend on full puppeteer and I will merge ndb-inspect to ndb, it should happen soon.

**Comment by ak239** [comment]
I removed ndb-inspect in https://github.com/GoogleChromeLabs/ndb/pull/167/commits/436c5f0d1cee3b205efe6bc88286856733e79fd3. Please follow https://github.com/GoogleChromeLabs/ndb/pull/167 for updates.

**Comment by ak239** [comment]
Fixed in most recent ndb@1.0.28, thanks for your report!

**Comment by josezulu** [comment]
@ak239 [436c5f0](https://github.com/GoogleChromeLabs/ndb/commit/436c5f0d1cee3b205efe6bc88286856733e79fd3) instructs to install ndb as local dev dependency. Is there a way presently to `node -r ndb/inspect index.js` while ndb installed globally?

**Comment by ak239** [comment]
Unfortunately in Node.js it is not possible to require globally installed module. It might be possible only with extending NODE_PATH environment variable [1].
[1] https://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package

**Comment by ak239** [comment]
Latest ndb@1.0.33 contains fix for ndb/inspect-brk. Thanks for your bug report.
