### ISSUE TITLE
 'Browser.grantPermissions' wasn't found

### ISSUE THREAD

**Issue by wanglong167** [GoogleChromeLabs/ndb#173]
* ndb version: v1.0.28
* Platform / OS version: w10
* Node.js version: v8.5.0
> ndb test.js

unhandledRejection Protocol error (Browser.grantPermissions): 'Browser.grantPermissions' wasn't found

**Comment by ak239** [comment]
Thanks for your report, what version of chrome do you have on your machine?
I will add a flag that forces chromium download tomorrow.

**Comment by wanglong167** [comment]
Google Chrome  69.0.3497.81

**Comment by ak239** [comment]
Is it possible to update Chrome to latest stable (70.0.3538.102) on your machine?

**Comment by wanglong167** [comment]
![image](https://user-images.githubusercontent.com/456516/48632859-f9655c00-e9fc-11e8-8699-2efc952d80d8.png)

**Comment by ak239** [comment]
Looks better, does Sources panel work?

**Comment by wanglong167** [comment]
![image](https://user-images.githubusercontent.com/456516/48633201-c7a0c500-e9fd-11e8-9d55-74cf35973473.png)

**Comment by ak239** [comment]
It does not look like it works. I will check windows.
