### ISSUE TITLE
Issue opening up standalone on OSX after recent update

### ISSUE THREAD

**Issue by mettese** [GoogleChromeLabs/ndb#177]
Eversince the update I've been having trouble with launching ndb.
Running 'ndb' in a terminal gives me the following error:
**unhandledRejection EACCES: permission denied, copyfile '/Users/sem/.ndb/ChromiumPreferences' -> '/var/folders/cv/lv3gz93d40s5w4t8f2x8jyhc0000gn/T/ndb-f2wHSk/Default/Preferences'**
The lv3gz...-folder is protected by osx SIP for some reason, not sure if it's supposed to be.

However, running 'sudo ndb' opens up a chrome inspector window instead of a chromium window:
![image](https://user-images.githubusercontent.com/44810285/48707904-38fc9580-ec01-11e8-96c9-9ad414aadb14.png)

* ndb version: 1.0.28
* Platform / OS version: macOS 10.14
* Node.js version: 8.12.0

I'm fairly certain this is an oversight on my end but I haven't found the issue yet.

**Comment by manobi** [comment]
In my case when I run ```ndb npm run api``` it says:

```shell
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/Users/manobi/myproject/run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

It seems it's understanding "npm run" as a module.

**Comment by ak239** [comment]
ndb@1.0.37 contains fix for `ndb npm run` use case but original issue requires additional investigation.

**Comment by ak239** [comment]
ndb@1.0.39 contains fix for original issue, feel free to comment here if you still can reproduce the problem and thanks for your report.

**Comment by manobi** [comment]
It worked for me, thanks.

**Comment by mettese** [comment]
Issue's solved, thanks for the fix!
