### ISSUE TITLE
I can't see files on Sources tab after upgrade to v1.0.28

### ISSUE THREAD

**Issue by navarroaxel** [GoogleChromeLabs/ndb#178]
### Steps to reproduce
I have been using `ndb@1.0.26`, when I run `ndb index.js` I can see the server files on the `sources/filesystem` tab on DevTools. After upgrade to `ndb@1.0.28` I can't see any file on my DevTools and I can't add folders to the workspace.

I have removed `nvm` and I reinstalled all again using several ways, but I can't find the issue. 

I have notice that `ndb@1.0.28` don't download the Chromium binary.

I have tried `NDB_DEBUG_FRONTEND=1 ndb index.js` but I didn't get any output.

A downgrade to `ndb@1.0.26` fix the issue.

**Tell us about your environment:**

* ndb version: 1.0.28
* Platform / OS version: Archlinux
* Node.js version: 10.13.0 (via nvm)

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. use ndb@1.0.26 and run a js file
2. update ndb using `npm i -g ndb`
3. use ndb@1.0.28 and run the same js file

**What is the expected result?**
I should see my server files on the `sources/filesystem` tab on DevTools

**What happens instead?**
The `node` server start correctly but I can't see any file on my DevTools and I can't add folders to the workspace.
A `node` process work at 125% of my 4 cores CPU (via top)
When I close the `ndb` window the `node` process does not stop and kill himself via out of memory.

**Comment by ak239** [comment]
Thanks for great bug report, I have speculative fix for this issue in canary channel, could you please install `npm install -g ndb@canary` and try to use it?
Please run `find . | wc -l' from terminal inside folder where you run ndb and dump result here as well.

**Comment by navarroaxel** [comment]
The bug looks fixed on `ndb@1.0.31`. I can see the source files and the `node` process exists with no CPU usage issues.

`find . | wc -l` -> `20026`

Thanks for your work!

**Comment by ak239** [comment]
Thank you!
Fixed by https://github.com/GoogleChromeLabs/ndb/commit/ca6ffdd996790ea5d348c4703ce3879cd4340041
