### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by laggingreflex** [GoogleChromeLabs/ndb#19]
### Steps to reproduce

**Tell us about your environment:**

* ndb version:  1.0.4
* Platform / OS version: Win10ProX64
* Node.js version: 10.5

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

Have a simple file 

**`index.js`**

```js
console.log('hi');
```

1. Run `ndb node index.js`

**What is the expected result?**

It should not display that error

**What happens instead?**

While launching it shows this error:

```
ndb node index.js
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Debugger listening on ws://127.0.0.1:65091/76c88dbd-da7b-4b65-bc3f-f629b3d13206
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

**Comment by ak239** [comment]
The issue here that we do not properly process spaces inside path to node binary on Windows. We will fix it soon.

**Comment by JimmyGY** [comment]
I think I meet the same problem, here is the error:

`ndb npm run dev`
`'C:\Program' is not recognized as an internal or external command, operable program or batch file.
'C:\Program Files\nodejs\\node.exe: Files\nodejs\node_modules\ndb\node_debug_demon\preload.js is not supported in NODE_OPTIONS'`

**Comment by ak239** [comment]
Please try 1.0.7. The issue should be fixed there :)
