### ISSUE TITLE
NDB broken after 1.0.26

### ISSUE THREAD

**Issue by heygrady** [GoogleChromeLabs/ndb#195]
- Mac OS 10.14.1
- Node 10.13.0
- Yarn 1.12.3

With 1.0.27 or higher ndb doesn't open/doesn't do anything at all.

```bash
yarn global remove ndb && \
yarn global add ndb@1.0.27 && \
ndb myscript.js
# nothing happens
```

With 1.0.26 or lower ndb opens fine and works as expected.

```bash
yarn global remove ndb && \
yarn global add ndb@1.0.26 && \
ndb myscript.js
Hello!
```

**myscript.js**
```js
console.log('Hello!')
```

**Comment by ak239** [comment]
Thanks for report.
What version of Chrome do you have installed on your machine?

**Comment by heygrady** [comment]
70.0.3538.110 (Official Build) (64-bit)

But I just upgraded. Didn't realize that mattered. Doesn't seem to help.

```bash
yarn global remove ndb && \
yarn global add ndb@1.0.36 && \
ndb myscript.js
# nothing happens
```

**Comment by marceloch2** [comment]
Same here - OSX

Google Chrome is up to date
Version 72.0.3625.0 (Official Build) canary (64-bit)

**Comment by marceloch2** [comment]
@ak239 kind of works but i can't see the screen i was used too, just a chrome tools white normal console.

**Comment by ak239** [comment]
If you still can reproduce this issue with `ndb@1.0.40` please left comment here or create new issue.
Thanks for your report!
