### ISSUE TITLE
TypeError: Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by ebidel** [GoogleChromeLabs/ndb#2]
Steps:

1. `npm install -g ndb`
2. Run `ndb script.js`:

<img width="741" alt="screen shot 2018-07-20 at 1 40 16 pm" src="https://user-images.githubusercontent.com/238208/43024222-738c4310-8c22-11e8-9c64-4cacb9c6b4fd.png">

**Comment by ak239** [comment]
Thanks!
This one should be fixed. This error related to old ndb package that most likely was not updated yet when you installed ndb.
