### ISSUE TITLE
Reload on NDB will cause address in use on debugging applications serving ports

### ISSUE THREAD

**Issue by ratacat** [GoogleChromeLabs/ndb#217]
I'm using ndb v1.0.37, and locally have Chrome Version 70.0.3538.110 (Official Build) (64-bit).

Trying to use ndb to attach to a local copy of Ranvier mud.
https://github.com/RanvierMUD/ranviermud

I start it with ndb ./ranvier
Which works fine. However, when I try and CMD + R in ndb to restart the server, it throws 

``` unhandledRejection Execution context was destroyed, most likely because of a navigation.```

And the server restarts, but it never seems to attache after that until I totally kill ndb.  Any thoughts?

**Comment by ratacat** [comment]
Okay, I'm pretty sure this issue is actually the same as this one.
#77 
I'm running node version v11.1.0
ndb@1.0.41
OSX 10.12.6 Sierra
And the application is running a telnet server on port 4000.

**Comment by ak239** [comment]
I checked `ndb@1.0.50` with `ranvier` and it works just fine to me. It looks fixes, feel free to comment this issue or open new one if it is still reproducible for you.
