### ISSUE TITLE
Syntax errors point to vm.js

### ISSUE THREAD

**Issue by pavelfeldman** [GoogleChromeLabs/ndb#219]
<img width="637" alt="screen shot 2018-12-04 at 9 20 32 pm" src="https://user-images.githubusercontent.com/883973/49491944-06f75000-f80b-11e8-8d1e-fdb335fbae4e.png">

**Comment by ak239** [comment]
Node internally catches and rethrow SyntaxError exception. It is fixed in Node 12.
