### ISSUE TITLE
UI flickering/flashing

### ISSUE THREAD

**Issue by dejan9393** [GoogleChromeLabs/ndb#222]
Not sure if this is an ndb issue or if it is better suited for a ticket at puppeteer.

**Tell us about your environment:**

* ndb version: v1.0.42
* Platform / OS version: macOS Mojave 10.14.1
* Node.js version: v11.2.0

**What steps will reproduce the problem?**

Randomly starts happening. Typically when switching tabs or scrolling through files navigator/inside a file's contents. I have dark mode enabled, may or may not be related.

I can sometimes temporarily alleviate the issue by zooming out/in, but the flashing will sporadically start again.

**What is the expected result?**
No flickering

**What happens instead?**
Flickering

![ndb-flickering](https://user-images.githubusercontent.com/13180986/49625607-536ca680-fa2a-11e8-825a-9729f7c7ed3b.gif)

**Comment by ak239** [comment]
Do you have local Chrome installed on your machine and if your so what version?

**Comment by dejan9393** [comment]
I actively use `Version 71.0.3578.80 (Official Build) beta (64-bit)`

I do however also have other versions installed

**Comment by ak239** [comment]
Please check out latest ndb - `ndb@1.0.48`. It uses recommended Chromium build so this flickering should go away.
