### ISSUE TITLE
ndb quits on pressing crtl+shift+A when adding selected text to watches in French Keyboard

### ISSUE THREAD

**Issue by linqOxelar** [GoogleChromeLabs/ndb#225]
### Steps to reproduce
0. work in French environnement in Windows and French  (from France) keyboard
1. select text
2. press crtl + shift+A

**Tell us about your environment:**

* ndb version: 1.0.42
* Platform / OS version: Windows 10 Family 64b 1809 17763.195
* Node.js version:10.14.2

**What is the expected result?**
add text to watches

**What happens instead?**
add text to watches AND close ndb

**HINT**
In French keyboard A is at Q key position in English keyboard... French are not QWERTY but AZERTY.
and crtl+shift+Q is used to quit in France/French keyboard.

**Comment by ak239** [comment]
This one is `carlo` bug, I open a pull request there and will update `carlo` in `ndb` as soon as it merged.
