### ISSUE TITLE
ndb is extremely slow when the working directory contains too many files

### ISSUE THREAD

**Issue by sighingnow** [GoogleChromeLabs/ndb#229]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.42
* Platform / OS version: Microsoft Windows 10.0.17134.472
* Node.js version: v11.3.0

**What steps will reproduce the problem?**

+ open a cmd in `C:\`
+ execute `ndb`
+ the chrome dev tools popup, however we cannot execute anything in console, and the cpu/disk usage is high
+ the problem above doesn't occur when execute ndb in a rather small directory (for example, `C:\Users\xxx\Desktop`)

**Comment by alexjesp** [comment]
Getting the same issue with this version of ndb

**Comment by chadkirby** [comment]
same problem with v1.0.43 in node x8.10.0 on osx. The process `ndb/file_system` will consume a whole core for several minutes until I tire of waiting & kill it. I thought that this problem only arose in large repos, but just now, I'm seeing the problem in a repo with a grand total of about 40 files (outside `node_modules`).

**Comment by blerik** [comment]
I'm on Linux (Nixos 18.09), and I see the same problem. It seems chokidar (which is used to stat and watch the filesystem) is very optimized for Mac, not so much for Windows / Linux (https://github.com/paulmillr/chokidar#how).

I see issues when the amount of files is bigger than about 1000. And node_modules goes over that number very quickly. So I 'patched' the code in my global node_modules (.local-frontend/ndb_app.js) to ignore the node_modules folder. That helps a bit.

Without that patch, a folder with 800 files opens in seconds, and one with 5000 files opens never (45 minutes of 100%+ cpu, and then I killed it).

**Comment by ak239** [comment]
`ndb@1.0.47` uses new version of `chokidar`. This version is much better optimized to work with huge file trees. Feel free to file another issue or leave a comment here if you still can reproduce this problem.
