### ISSUE TITLE
Does not install properly with Yarn

### ISSUE THREAD

**Issue by jacob-israel-turner** [GoogleChromeLabs/ndb#23]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.6, attempted v1.0.5, v1.0.4, and v1.0.3 as well
* Platform / OS version: MacOS High Sierra 10.13.3
* Node.js version: Attempted with both v8.9.4 and v10.7.0

**What steps will reproduce the problem?**

1. Run `ndb .` or `ndb <filename>.js`
2. `ndb` does indeed launch, but only shows a black window.

**What is the expected result?**

The proper debugger UI should show up.

**What happens instead?**

None of the UI renders.

<img width="1200" alt="screen shot 2018-07-22 at 9 00 23 pm" src="https://user-images.githubusercontent.com/8698364/43055175-55aa202a-8df2-11e8-9463-8c460c9f3a39.png">

**Comment by ak239** [comment]
Thanks for your report!
Are there any errors in terminal? Could you please go to View menu for ndb window, open DevTools from there and check are there any errors in DevTools console?
Could you try to press Ctrl+R inside ndb window, will it force UI to be loaded?

**Comment by jacob-israel-turner** [comment]
Thanks for the quick reply!

Nothing in the console, and reloading just shows the same blank UI.

<img width="728" alt="screen shot 2018-07-22 at 9 30 43 pm" src="https://user-images.githubusercontent.com/8698364/43055948-9abfe5a6-8df6-11e8-93c5-b450d7ab846c.png">
<img width="727" alt="screen shot 2018-07-22 at 9 30 10 pm" src="https://user-images.githubusercontent.com/8698364/43055949-9ad42da4-8df6-11e8-936c-99a186918e91.png">

**Comment by mohdasim** [comment]
Getting the same error on Ubuntu 16.04 also.
ndb version: v1.0.6
Platform / OS version: Ubuntu 16.04
Node.js version: 8.11.3

**Comment by jackharrhy** [comment]
MacOS High Sierra 10.13.5, close to the same error.
- Node.js version v8.11.3 leaves me with a blank screen and an empty console in inspect element.
- But Node.js version v10.5.0 works seemingly fine

**Comment by mavame** [comment]
I'm experiencing this on `MacOS High Sierra 10.13.4` and `node/10.7.0` and here's what I see in my console after running `ndb` (with and without arguments):

```
(node:28405) UnhandledPromiseRejectionWarning: Error: Cannot find module './.local-frontend/ndb_app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)    at main (/usr/local/lib/node_modules/ndb/ndb.js:83:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ak239** [comment]
@mavame , could you try to run ndb with NDB_DEBUG_FRONTEND=1 flag?
```bash
NDB_DEBUG_FRONTEND=1 ndb .
```

**Comment by fooey** [comment]
Also getting a blank screen on macOS, running it with `NDB_DEBUG_FRONTEND` gave me this:

```
$ NDB_DEBUG_FRONTEND=1 ndb .
Debugger listening on ws://127.0.0.1:57170/c22c9957-6780-4179-bee2-8bb00d3f6144
For help see https://nodejs.org/en/docs/inspector
(node:98311) UnhandledPromiseRejectionWarning: Error: Cannot find module 'chrome-devtools-frontend/front_end/node_modules/xterm/dist/xterm.css'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at requestIntercepted (/Users/jasonrushton/.config/yarn/global/node_modules/ndb/ndb.js:214:24)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at NetworkManager.Page._networkManager.on.event (/Users/jasonrushton/.config/yarn/global/node_modules/puppeteer/lib/Page.js:122:74)
    at emitOne (events.js:116:13)
    at NetworkManager.emit (events.js:211:7)
    at NetworkManager._handleRequestStart (/Users/jasonrushton/.config/yarn/global/node_modules/puppeteer/lib/NetworkManager.js:221:10)
    at NetworkManager._onRequestIntercepted (/Users/jasonrushton/.config/yarn/global/node_modules/puppeteer/lib/NetworkManager.js:169:12)
(node:98311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:98311) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Debugger attached.```

**Comment by ak239** [comment]
@fooey , thank you. It looks like ndb installation failed.
Could you try to reinstall ndb and dump install log?
```bash
npm -g uninstall ndb && npm install -g ndb
```

**Comment by fooey** [comment]
I installed it using yarn originally, but I uninstalled it and used npm instead, and it does seem to be working now.

**Comment by jacob-israel-turner** [comment]
> I installed it using yarn originally, but I uninstalled it and used npm instead, and it does seem to be working now.
Uninstalled it from npm, and tried again with yarn to see if it generated any logs, but it works now. Don't know why it wasn't happy before, but thanks for the help.

I just tried this as well, and it's working just fine for me now.  Sounds like maybe yarn skips some dependency or compile step on the first go, but npm handles it fine.  In any case, my most recent install of ndb with yarn is working fine now.

**Comment by ak239** [comment]
Thanks! We will take a look into installing with yarn.

**Comment by jstewmon** [comment]
I'm seeing this intermittently using npm to [un]install.

- First install on a new machine this morning with `npm install -g ndb` resulted in blank screen.
- Reinstall with `npm -g uninstall ndb && npm install -g ndb` fixed.
- Reinstall with `npm -g uninstall ndb && npm install -g ndb` to update to 1.0.7 resulted in blank screen again.
- Reinstall with `npm -g uninstall ndb && npm install -g ndb` fixed.

**Comment by ak239** [comment]
1.0.9 should contain fix for yarn and black screen. I will be happy to get feedback! Feel free to reopen this one if it is still reproducible.

**Comment by jacob-israel-turner** [comment]
@ak239 I encountered this issue again today, running a fresh install through yarn on a fresh Ubuntu 18.04 installation.  Removing, installing with npm, removing, then installing with yarn again fixed it, as before.
