### ISSUE TITLE
Source maps don't work for forked files (but the first file)

### ISSUE THREAD

**Issue by restrry** [GoogleChromeLabs/ndb#232]
If I fork several process and try to debug them I can see the source code with applied source maps only for the first worker. For other workers `ndb` doesn't show source code at all.
### Steps to reproduce

**Tell us about your environment:**
* ndb version: 1.0.42
* Platform / OS version: macOS Mojave v10.14.2
* Node.js version: v10.14.1

**What steps will reproduce the problem?**

1. clone repo https://github.com/restrry/ndb-error-demo/
2. install deps and run the project
3. open in browser http://127.0.0.1:1340/

**What is the expected result?**
ndb shows the source code with debugger statement (as it works for the first worker, to check - open http://127.0.0.1:1337/)
![2019-01-17_10-51-39](https://user-images.githubusercontent.com/3198181/51311924-61aadb00-1a4a-11e9-844f-d1bb4866b182.png)

**What happens instead?**
ndb pauses execution, but the source code is not rendered on the screen (to check open http://127.0.0.1:1340/)
![2019-01-17_10-51-12](https://user-images.githubusercontent.com/3198181/51311964-77200500-1a4a-11e9-8e1f-48f00b968aa6.png)

**Comment by heygrady** [comment]
Came here to report the same thing. Reverting to 1.0.26 makes everything work. Every release since 1.0.26 has been broken in one way or another.
