### ISSUE TITLE
Live edit

### ISSUE THREAD

**Issue by csakaszamok** [GoogleChromeLabs/ndb#236]
it will contains live edit ?
(like https://umaar.com/dev-tips/119-node-js-hot-code-swap/)

**Comment by ak239** [comment]
It should work already in some simple cases, unfortunately live edit implementation inside V8 requires improvements, e.g. support for patching generators (crucial for async/await).

**Comment by csakaszamok** [comment]
Any news?

**Comment by ak239** [comment]
Node.js and Chromium use V8 engine. LiveEdit implementation is located inside it so `ndb` should support LiveEdit on the same level as `Chrome` support it for web.
I will mark it as fixed. If liveedit does not work in your use case, it is most likely should be filled as feature request in V8 bug tracker.
