### ISSUE TITLE
ndb window stays empty

### ISSUE THREAD

**Issue by gagoar** [GoogleChromeLabs/ndb#242]
👋 
### Steps to reproduce

**Tell us about your environment:**

* ndb version: v1.0.43
* Platform / OS version: MacOS 10.14.3
* Node.js version: v8.10.0
* Chrome Version:  72.0.3626.121 (Official Build) (64-bit)
* Chrome Canary Version:  74.0.3723.0 (Official Build) canary (64-bit)
* nvm version: 0.30.2

**What steps will reproduce the problem?**
1) npm install -g ndb@1.0.43
2) ndb yarn start/test (in any project I have with these hooks)

**What is the expected result?**
ndb to show the dev-tools screen  

**What happens instead?**

shows a blank screen: 
<img width="1201" alt="ndb-start" src="https://user-images.githubusercontent.com/226559/53703959-3139b900-3dcc-11e9-8b64-99f32c1c99f0.png">

inspecting the window, I see errors in the console:
<img width="1065" alt="ndb-console-error" src="https://user-images.githubusercontent.com/226559/53703961-3dbe1180-3dcc-11e9-8d8b-22f8ddaa8db0.png">

``` javascript
ndb_app.js:3 Uncaught TypeError: document.registerElement is not a function
    at Object.UI.registerCustomElement (ndb_app.js:3)
    at ndb_app.js:3
    at ndb_app.js:3
```
no errors in the terminal (when invoking ndb)

I've also tried with:
- ndb version: 1.0.42, 1.0.41
- Node.js version: v10.15.2

**Comment by bjrmatos** [comment]
i have the same error using OSX El Capitan

**Comment by Hoten** [comment]
Same issue. I did a bisect on the release versions and found `1.0.26` seemed to be the last version that works.

```
node v8.12.0
MacOS Mojave 10.14.3
```

**Comment by brendankenny** [comment]
Looks like this is due to Shadow DOM v0 being removed - https://www.chromestatus.com/features/4507242028072960. Either a polyfill will have to be added or update to the shipping standard.

What does DevTools itself do?

**Comment by Hoten** [comment]
Works fine on my Debian machine.

**Comment by gagoar** [comment]
> 1.0.26

It looks like the version 1.0.26 uses chromium and the 1.0.43/42/41 uses chrome already in installed in the computer.

**Comment by Hoten** [comment]
Perhaps `carlo` changed how it launches Chrome during those releases.

But, I've just tried it again and the latest Canary `74.0.3726.0` works.

**Comment by gagoar** [comment]
> Perhaps `carlo` changed how it launches Chrome during those releases.
> 
> But, I've just tried it again and the latest Canary `74.0.3726.0` works.

I wonder if it would be better to be able to select the browser we want to use with ndb. Maybe having the chance to change what chrome is used would simplify how we troubleshoot 🤔

**Comment by paulirish** [comment]
.

> What does DevTools itself do?

devtools got an exception. there's an origin trial for avoiding the removal of shadow Dom v0. I don't know if origin trials would understand a Carlo window.
