### ISSUE TITLE
ndb does not exit when closing the window

### ISSUE THREAD

**Issue by hediet** [GoogleChromeLabs/ndb#250]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.44
* Platform / OS version: Windows
* Node.js version: 11.8.0

**What steps will reproduce the problem?**

1. `yarn global add ndb`
2. `ndb`
3. Close the (single) ndb window

**What is the expected result?**
The `ndb` command returns.

**What happens instead?**
The `ndb` command is still running.

**Comment by ak239** [comment]
It looks fixed in `1.1.0`. Feel free to comment if you still can reproduce this issue.
