### ISSUE TITLE
resolving issues label:enhancement 

### ISSUE THREAD

**Issue by jimmont** [GoogleChromeLabs/ndb#274]
Related to contributing:
When closing an issue that is a bug/defect, please allow a window of time for soliciting feedback and confirmation of resolution. Perhaps 3 working days--neither too much or too little time for engaged reporters across time zones.

Further, it would be helpful to know if PRs being approved are actually run, and demonstrate resolution of the work justifying the changes. (This does not appear to be happening in a cursory check, see #269 and #271.)

Background:
There is a cost associated with making the software.
There is a cost associated with supporting the software, including reporting problems and fixing the same.
Allowing time and a practical process in which this can occur is important for product effectiveness.

**Comment by ak239** [comment]
Thank you for your feedback. When I am working with issues, I use the following process:
1. reproduce the bug, if there are no detailed steps, I do my best to reproduce it based on the provided information,
1. fix the problem and check that the fix helps with the issue that I can reproduce,
1. GitHub automatically marks mentioned bug as fixed,
1. release a new patch version with fix,
1. put a comment in a bug that fixes is available in given version and wait for verification from the reporter,
1. if the reporter does not verify fix inside their environment, I reopen a bug and repeat process from the start.

I believe that the most significant improvement in this process - I can achieve by introducing adding mandatory regression test with a fix.

In general if something is not fixed it means that I failed with proper reproduction of the issue.
