### ISSUE TITLE
REPL process is not stopped when ndb window is closed.

### ISSUE THREAD

**Issue by jstewmon** [GoogleChromeLabs/ndb#28]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: `ndb@1.0.4`
* Platform / OS version: `Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64`
* Node.js version: `v8.11.3`

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run ndb
2. Close ndb window
3. Run `ps | grep ndb/lib/repl`

**What is the expected result?**
No processes should be shown.

**What happens instead?**
The node process running the repl is still running.

**Comment by ak239** [comment]
Please try 1.0.7. This issue should be fixed there.

**Comment by jstewmon** [comment]
Indeed, with 1.0.7, all related node processes are stopped when chromium is closed. Thanks!

**Comment by ak239** [comment]
@Diluka could you provide more details, e.g. sample script?

**Comment by Diluka** [comment]
my express server has some resource connections can't close gracefully. 
On macOS, it will running background, but Windows not.

**Comment by ak239** [comment]
Please check latest ndb version (1.0.25)? It handles inspected processes better on shutdown.
