### ISSUE TITLE
Feature request: Start new sessions in ndb terminal

### ISSUE THREAD

**Issue by jeremyckahn** [GoogleChromeLabs/ndb#29]
I love that ndb provides a CLI — it opens the door to ndb being a full JavaScript IDE! I think it can be tweaked to be even more useful than it already is.

### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.6
* Platform / OS version: OS X 10.13.6
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

In ndb's terminal, run `exit`. The session is ended and cannot be restarted without reloading ndb.

_Please include code that reproduces the issue._

1. `exit`, or `ctrl+d`

**What is the expected result?**

I can start a new shell session either manually or automatically.

**What happens instead?**

I have to restart ndb to get a new  session.

**Comment by ak239** [comment]
fixed only on mac.

**Comment by jeremyckahn** [comment]
ndb@1.0.8 is working perfectly for me. Thanks so much for the quick response and implementation @ak239!
