### ISSUE TITLE
Where's the path to put the chromium manually if the installation of ndb (GoogleChromeLabs/ndb) did not complete?

### ISSUE THREAD

**Issue by MAXIIIMVS** [GoogleChromeLabs/ndb#307]
# Where's the path to put the chromium manually if the installation of ndb (GoogleChromeLabs/ndb) did not complete?

Hi.
I was trying to install ndb globally, but I couldn't install it properly. ndb depends on Puppeteer which downloads a recent version of Chromium. My machine could not download chromium because the URL for downloading it was blocked. So I downloaded chromium (chrome.zip) manually, but I don't know where I should put the chrome-win folder. I'm using windows 7. I would appreciate any help. Thanks

**Comment by MAXIIIMVS** [comment]
Hello, is anyone there?

**Comment by eaviles** [comment]
@Mustafa-Hayati hope this helps… mine is installed here:
/node_modules/ndb/node_modules/carlo/lib/.local-data/

under a "mac-624492" folder (for Chromium r624492)

**Comment by eaviles** [comment]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/182510/76343645-cb351b00-62d6-11ea-9bbb-9918e3be2d61.png">

**Comment by MAXIIIMVS** [comment]
@eaviles thanks
