### ISSUE TITLE
ndb closes instantly after launch (Ubuntu)

### ISSUE THREAD

**Issue by j-koziel** [GoogleChromeLabs/ndb#336]
I've installed it locally, globally and as a dev dependency but to no avail.

**Tell us about your environment:**

* ndb version: 1.1.5
* Platform / OS version: Ubuntu 22.04 Jammy Jellyfish, window manager: bspwm, compositor: picom
* Node.js version: 16.15.0

**What steps will reproduce the problem?**

package.json file
`{
  "name": "natours",
  "version": "1.0.0",
  "description": "Learning node, express and mongoDB",
  "main": "app.js",
  "scripts": {
    "start": "nodemon server.js",
    "start:prod": "NODE_ENV=production nodemon server.js",
    "debug": "ndb server.js"
  },
  "author": "Jonathan Koziel",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^16.0.0",
    "express": "^4.17.3",
    "mongoose": "^5.13.14",
    "morgan": "^1.10.0",
    "slugify": "^1.6.5",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "eslint": "^8.13.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "ndb": "^1.1.5",
    "prettier": "^2.6.2",
    "puppeteer-core": "^14.1.1"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}`

**What is the expected result?**
ndb should open and work

**What happens instead?**
ndb opens a window and disappears immediately after.
Video:

https://user-images.githubusercontent.com/68497216/169686127-b13dde7a-a50b-497a-ae6f-44d39808ac59.mp4

When I use sudo no window opens but instead i get an error mentioned in a previous issue.
Error log:
sudo ndb server.js                                                                                                                                                                                                    
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by davidsu** [comment]
+1

**Comment by AmritPant** [comment]
Hey, 
I am also in Jonas's course, I also had a similar issue to fix this issue 

It Is because Chrome cannot be run as root by default.
A workaround is to install ndb in a directory that doesn't require elevated permissions.


`npm uninstall --location=global ndb`   // UNINSTALL IT 

`npm install --location=global --prefix=$HOME/.npm ndb`  // INSTALL IT ON SEPRATE DIRECTORY

`vim ~/.bashrc  `   // OPEN .bashrc file in any code editor .. ONLY if you are using bash or ZSH if you are using FISH then ~/.config/fish/config.fish

`PATH=$PATH:"$HOME/.npm/bin".` // Add the PATH VARIABLE TO .bashrc FILE

**Comment by j-koziel** [comment]
I tried doing that after I saw this comment on another issue (#312) but it did not work for me either.

I think i am just going to close this issue as I have made my return back to windows and it seems as if this package is no longer being maintained (#334)

**Comment by j-koziel** [comment]
Thanks for the suggestion 👍

**Comment by AmritPant** [comment]
@j-koziel Welcome
