### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by GoBrianGo** [GoogleChromeLabs/ndb#36]
I hava a problem when I installed ndb,here is the error message
` TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
`

**Comment by ak239** [comment]
Could you dump full `npm install` log?

**Comment by ak239** [comment]
Please try ndb 1.0.9. It may help, otherwise please provide more details about your Node.js environment.

**Comment by GoBrianGo** [comment]
I try ndb 1.0.9,but it still failed.Here is the error message.
/Users/Brian/.nvm/versions/node/v8.3.0/bin/ndb -> /Users/Brian/.nvm/versions/node/v8.3.0/lib/node_modules/ndb/ndb.js

> ndb@1.0.9 postinstall /Users/Brian/.nvm/versions/node/v8.3.0/lib/node_modules/ndb
> node install.js

(node:40092) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
(node:40092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ ndb@1.0.9
updated 1 package in 26.317s

**Comment by ak239** [comment]
ndb was updated few hours ago and 1.0.10 contains a fix for this issue. Thank you for your report!
