### ISSUE TITLE
cannot attach debugger to subprocesses. error

### ISSUE THREAD

**Issue by brizer** [GoogleChromeLabs/ndb#37]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: latest
* Platform / OS version:  mac osx 10.12.1
* Node.js version:  8.9.1 

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

when i debugger to this step:

    var exec = require('child_process').exec;
    var child = exec(cmd, {
        maxBuffer: 1024 * 1024
    });

    child.stdout.on('data', function(out) {
        callback(0.9, out);
    });
    child.stderr.on('data', function(err) {
        console.error(err);
        callback(0.9, 'nej打包错误，信息为：' + err);
    });

**What is the expected result?**
it should be ok, just like i do same in intellij.

**What happens instead?**
but it erros:

Debugger listening on ws://127.0.0.1:60041/cf319e02-496b-4ebc-82cc-ca199c2337b0
For help see https://nodejs.org/en/docs/inspector
Debugger attached.

How to solve this problem ??

**Comment by ak239** [comment]
Could you provide a little more details? What command you pass to exec? What do you mean by it should be ok?
The attached output is not an error by itself it just means that ndb successfully connected to child process.

**Comment by brizer** [comment]
I found the question. 
The callback is base on socket.io, such as:

// 监听发布专题


        socket.on("publish", function (data) {

            api.publish(data.name, function (progress,info) {

                io.to(data.name).emit("publishProgress",{
                    progress:progress,
                    info:info
                });
            });
        });



If I  remove the callback ,it can be success:



    var exec = require('child_process').exec;
    var child = exec(cmd, {
        maxBuffer: 1024 * 1024
    });

    child.stdout.on('data', function(out) {
        //callback(0.9, out);
    });
    child.stderr.on('data', function(err) {
        //console.error(err);
        //callback(0.9, 'nej打包错误，信息为：' + err);
    });
    child.on('close', function(code) {
        //callback(0.9, 'nej打包完成，信息为：' + code);

        if (!!done) {
            done();
        }
    });




so how to solve the problem? If my code is base on socket.

**Comment by ak239** [comment]
Could you provide command how do you start ndb and what exactly error do you get?

**Comment by ak239** [comment]
Feel free to reopen this issue with more details!
