### ISSUE TITLE
Feature Request: Whitelist some packages from node_modules

### ISSUE THREAD

**Issue by serkanyersen** [GoogleChromeLabs/ndb#45]
We have custom internal packages we use in our company. Most of the time I need to put a breakpoint in these packages while debugging.

All our packages are scoped, so if there was a way to whitelist `node_modules/@scope` it would be very useful.

At the moment, I can't see anything under node_modules.

**Comment by ak239** [comment]
I will fix it by showing everything from node_modules. It is a little blocked by introducing better way to fs.watch for changes inside folders, current way does not support a lot of folders and unfortunately node_modules usually contains a lot.

**Comment by CyberPhoenix90** [comment]
Showing eveything from node_modules is not great in my opinion, in some projects that will mean showing thousands of files that aren't relevant to the person debugging.

**Comment by ak239** [comment]
I just published version (1.0.11) that should resolve this issue:
1.  run `ndb` from folder with your project,
1. go to settings tabs, open node_modules tab, wait a little,
1. set Whitelist next to module that you would like to be able to debug,
1. restart ndb, you should get node_modules/dependency in navigator view, debugger will pause inside this dependency as usual.
I am looking forward for your feedback. 😄

**Comment by serkanyersen** [comment]
@ak239 Thanks for the change. I've just tested this feature on some projects but I'm not sure if I could get it working properly.

On one project, I'm able to see the packages, but after whitelisting they don't show up on file tree.


<img width="451" alt="screen shot 2018-07-26 at 10 36 10" src="https://user-images.githubusercontent.com/30582/43278431-f75f161c-90bf-11e8-96dc-6287142b3bf5.png">

on another project, it wouldn't even show the package list.

<img width="918" alt="screen shot 2018-07-26 at 10 35 30" src="https://user-images.githubusercontent.com/30582/43278462-0cf8ed9a-90c0-11e8-93c4-f3a608347f25.png">
You can see the packages are installed on this project.

but overall, this is exactly what I wanted.

**Comment by ak239** [comment]
First bug most likely related to at sign and I can reproduce it locally, fix will be available soon.
To fetch list of dependencies we run `npm ls --json` inside folder where ndb was started. Could you confirm that when you run this command for second project it runs without errors?

**Comment by serkanyersen** [comment]
it seems to work, here is the end of the output

<img width="600" alt="screen shot 2018-07-26 at 10 50 48" src="https://user-images.githubusercontent.com/30582/43279088-d5a36990-90c1-11e8-867a-d606a88b8172.png">


I'm guessing these extraneous: package errors are preventing you from parsing the output. Those error logs are definitely are in the `stderr` though, because they disappear when I run the command like this `npm ls --json 2>/dev/null`

**Comment by ak239** [comment]
Thanks a lot! It helps me detect the problem.

**Comment by ak239** [comment]
Please check out latest version (1.0.12). It contains fix for both problems.

**Comment by serkanyersen** [comment]
it works!! 👍 Thanks!!
