### ISSUE TITLE
ESM module --experimental-modules error

### ISSUE THREAD

**Issue by lomocc** [GoogleChromeLabs/ndb#49]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.9
* Platform / OS version: Windows 7
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

```js
// index.mjs
import './hello';
import './world';

// hello.mjs
console.log('hello');

// world.mjs
import './hello';
console.log('world');
```
_Please include code that reproduces the issue._

```js
$ ndb node --experimental-modules index.mjs
```

**What is the expected result?**

```
// log
hello
world
```

**What happens instead?**

```js
// error
module.js:468 Error: linking error, dependency promises must be resolved on instantiate
    at checkComplete (internal/loader/ModuleJob.js:75:27)
    at moduleJob.linked.then (internal/loader/ModuleJob.js:58:11)
    at <anonymous>
catch @ module.js:468
Promise rejected (async)
Module._load @ module.js:467
Module.runMain @ module.js:693
startup @ bootstrap_node.js:188
(anonymous) @ bootstrap_node.js:609
Show 5 more blackboxed frames
```
---

I try:

```js
// index.mjs
import './world';
import './hello';
```
then it works.

or if I don`t use ndb, it works well.

```js
$ node --experimental-modules index.mjs
```

**Comment by ak239** [comment]
Thanks for your report.
Please update your node. It works just fine for node 8.11.3 and node 10.7.0. If it still does not work, feel free to reopen this issue.
