### ISSUE TITLE
Welcome message in the console not visible in light theme

### ISSUE THREAD

**Issue by adrian-bobev** [GoogleChromeLabs/ndb#50]
* ndb version: 1.0.9
* Platform / OS version: macOS High Sierra 10.13.6
* Node.js version: **10.7.0**

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
1. Run **ndb server.js**
2. Change the theme to light

**What is the expected result?**
The welcome message: "Welcome to the ndb REPL!" is with white text and is not readable on the white background.

**What happens instead?**
The message white on white background and is not visible

**Comment by ak239** [comment]
New ndb version (1.0.11) with fix was published to npm. Thanks for your report!

**Comment by Hypnosphi** [comment]
Stupid question: how do you change the theme?
