### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by koljakutschera** [GoogleChromeLabs/ndb#51]
`
...
> node scripts/install.js

(node:40116) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ndb/node_modules/ndb-node-pty-prebuilt/build'
(node:40116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> puppeteer@1.6.1 install /usr/local/lib/node_modules/ndb/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r575458! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ndb/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/ndb/node_modules/puppeteer/.local-chromium' }
`

### Steps to reproduce

sudo npm install -g ndb

**Tell us about your environment:**

Mac OS 10.13.4

* ndb version: latest
* Platform / OS version: Mac
* Node.js version: 8.11.2

**What steps will reproduce the problem?**

Try to install using npm with or without sudo...

**What is the expected result?**

Should install

**What happens instead?**

Throws some permission errors...

**Comment by ak239** [comment]
Please take a look on https://github.com/GoogleChromeLabs/ndb/issues/20, some possible solutions are mentioned there.

**Comment by dark-swordsman** [comment]
I am having a similar issue, but I don't think it has anything to do with puppeteer and more so ndb. However, it may also be because I am using WSL. None of those solutions worked for me.

I had an issue where Cypress couldn't open up it's window, but I was able to download a network monitor/window program to access the browser from Windows. This doesn't seem to work with ndb.

```
> ndb firebase serve

Downloading Chromium r624492...
ERROR: Failed to download Chromium r624492!
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ndb/node_modules/carlo/lib/.local-data'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/ndb/node_modules/puppeteer-core/lib/helper.js:108:27)
    at downloadChromium (/usr/lib/node_modules/ndb/node_modules/carlo/lib/find_chrome.js:194:50)
    at findChrome (/usr/lib/node_modules/ndb/node_modules/carlo/lib/find_chrome.js:241:32)
    at Object.launch (/usr/lib/node_modules/ndb/node_modules/carlo/lib/carlo.js:594:42)
    at launch (/usr/lib/node_modules/ndb/lib/launcher.js:23:23)
    at Object.<anonymous> (/usr/lib/node_modules/ndb/ndb.js:35:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/ndb/node_modules/carlo/lib/.local-data' }
unhandledRejection TypeError: Cannot read property 'executablePath' of null
    at findChrome (/usr/lib/node_modules/ndb/node_modules/carlo/lib/find_chrome.js:242:43)
    at <anonymous>
```

I figured I would post in this issue since it's the top issue when you google `ndb ERROR: Failed to download Chromium r624492!`

**Comment by thijsdegaaij** [comment]
I have same problem. Anybody?

**Comment by thijsdegaaij** [comment]
> I have same problem. Anybody?

I deleted a Chrome Extension, that helped

**Comment by liuliangsir** [comment]
@dark-swordsman you can try [it](https://stackoverflow.com/a/55048094/4441984)
