### ISSUE TITLE
Does not work with node 8.4.0 and npm 6.0.0

### ISSUE THREAD

**Issue by adrian-bobev** [GoogleChromeLabs/ndb#52]
Installing ndb throw an error  in postinstall step:

> > ndb@1.0.9 postinstall /Users/<user>/.nvm/versions/node/v8.4.0/lib/node_modules/ndb
> > node install.js
> 
> (node:90479) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
> (node:90479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> + ndb@1.0.9
> added 167 packages from 107 contributors in 22.089s

After that everytime I try to run ndb command the following error occured:

> internal/util.js:206
>     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
>     ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
>     at Object.promisify (internal/util.js:206:11)
>     at Object.<anonymous> (/Users/<user>/.nvm/versions/node/v8.4.0/lib/node_modules/ndb/ndb.js:21:25)
>     at Module._compile (module.js:573:30)
>     at Object.Module._extensions..js (module.js:584:10)
>     at Module.load (module.js:507:32)
>     at tryModuleLoad (module.js:470:12)
>     at Function.Module._load (module.js:462:3)
>     at Function.Module.runMain (module.js:609:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:598:3

**Tell us about your environment:**

* ndb version: **1.0.9**
* Platform / OS version: **macOS High Sierra 10.13.6**
* Node.js version: **8.4.0**

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. run **npm install -g ndb**
2. run **ndb**

**What is the expected result?**
The DevTools should be opened

**What happens instead?**
Error is thrown in the console

**Comment by pedrocalderon** [comment]
+1

**Comment by ak239** [comment]
If it is possible to you then please update Node.js to 8.9.0.The problem that we use fs.copyFile and this method is available only since 8.5.0.

**Comment by pedrocalderon** [comment]
Worked for me

**Comment by ak239** [comment]
ndb 1.0.10 published and contains fix. Thank you for your report!
