### ISSUE TITLE
Question: How to map ./src to ./dist for transpiled code?

### ISSUE THREAD

**Issue by mattslight** [GoogleChromeLabs/ndb#57]
Amazing project please keep up the fantastic work supporting the Node.js community.

My build process runs babel (ES6 -> ES5 e.g. `./src` builds to `./dist` and Node serves from dist), it generates source maps and uses the source mapping in Node to allow me to see generated runtime errors indexed against original ES6 src files.

Can I ask `ndb` to also read those sourcemaps and allow me to set e.g. breakpoints in `./src` and do debugging there?

Thanks in advance.

**Comment by Maayu2415** [comment]
จะติดได้อย่างไร

**Comment by ak239** [comment]
Thanks for your report. If you can provide simple packa

**Comment by ak239** [comment]
Thanks for your report. We will take a look at source map related issues soon!

**Comment by ak239** [comment]
I checked examples with babel transpilation and it works in latest 1.0.20. Please try latest ndb version.
If something still does not work, feel free to provide details and reopen this issue.

**Comment by PascalPrecht** [comment]
@ak239 so I just tried this with 1.0.26 and it doesn't seem to pick up the breakpoints set in source at all.

Anything that needs to be done to enable this?

**Comment by mattslight** [comment]
Actually I didn't try with the breakpoints.
