### ISSUE TITLE
(node:45413) [DEP0018] Deprecation

### ISSUE THREAD

**Issue by sara0871** [GoogleChromeLabs/ndb#59]
### Steps to reproduce

**Tell us about your environment:**

* ndb version:
* Platform / OS version:
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by ak239** [comment]
Please, fill the template next time when you file an issue. :)
