### ISSUE TITLE
Reload on file change?

### ISSUE THREAD

**Issue by joacim-boive** [GoogleChromeLabs/ndb#61]
I like to use nodemon as it watches and restarts the script on change.

I could do nodemon --exec "ndb server.js" and that works.
But the problem is that if I change a file in the ndb debugger - nodemon detects the changed file and restarts the whole app.

I would very much prefer that ndb simply restarts the evaluation of the current file, as it currently does.

A nice feature would be if ndb implemented file watching without reloading the entire app when a file within the app is modified.

Other than that small grudge it's really slick! :)

**Comment by ak239** [comment]
I believe that you can change order of arguments and it should just work, please try following:
```bash
ndb nodemon --exec "node server.js"
```
Will it work for you? I will put it into readme if it works.

As alternative you can run your server using ndb:
```bash
ndb server.js
```
And then reload your server when you need it by pressing Ctrl+R or Cmd+R.

**Comment by joacim-boive** [comment]
Running just "ndb server.js" was perfect in my use case - thanks!

Now it both works modifying the file in my IDE (ndb detect the change and reloads that particular file) or modifying directly in ndb as usual.

Awesome!
