### ISSUE TITLE
breakpoints set via the GUI don't stop code execution

### ISSUE THREAD

**Issue by gkaindl** [GoogleChromeLabs/ndb#67]
ndb doesn't stop at breakpoints set via the GUI at all for me, using the tool versions below.

I'm running node with the --experimental-modules flag to use ES6 modules without transpiling them, so this is a "vanilla" configuration without any webpack or similar build tools in between.

I'm having the same problem with the dev tools in Chrome 66+, too, even though Chrome 65 still works fine.

### Steps to reproduce

* ndb version: v1.0.13
* Platform / OS version: macOS 10.12.6
* Node.js version: v10.7.0

**What steps will reproduce the problem?**

Launching the node app via the ndb command line tool or launching ndb first, then starting the node app from within it – it doesn't matter. Breakpoints set via the GUI don't work.

Other breakpoints, such as the launch breakpoint, *do* work, though.

**What is the expected result?**

Breakpoints set via GUI should cause execution to stop when they are hit.

**What happens instead?**

Breakpoints are ignored.

**Comment by ak239** [comment]
1.0.14 with fix just published. Breakpoints inside --experimental-modules should work just fine. Thanks for your report!
