### ISSUE TITLE
Reload ndb will cause EADDRINUSE in web application

### ISSUE THREAD

**Issue by 329530588** [GoogleChromeLabs/ndb#77]
### Steps to reproduce

1. Use ndb run an application listening a port.
2. command + r (OSX) in ndb
3. EADDRINUSE

* ndb version: latest
* Platform / OS version: OSX
* Node.js version: 8.11.3

**What is the expected result?**
Release the port when reloading

**Comment by ak239** [comment]
Thanks for your report!
Ctrl + R on Linux/Windows and Cmd + R behave much better in published 1.0.16.
