### ISSUE TITLE
Add ndb environment variable to process.env

### ISSUE THREAD

**Issue by jdalton** [GoogleChromeLabs/ndb#80]
Some loaders/utils could modify their behavior when they know they're being run in an inspector, e.g. to enable inline source maps. It would be helpful to be able to easily detect if the code is running in the inspector. One way to do this is to add an `ndb` value to `process.env` or to add its version key to `process.versions`.

**Comment by ak239** [comment]
When process is started from ndb, it has `process.env.NDD_PID` environmental variable, will it be enough for loaders/utils use case?

**Comment by jdalton** [comment]
Yep, that can be used. What does `NND` stand for?

**Comment by ak239** [comment]
It is stand for node_debug_demon. We use this demon to discover node processes and sub processes.
I will add process.env.NDB_VERSION today to make it cleaner.
