### ISSUE TITLE
ndb ignore .git folder

### ISSUE THREAD

**Issue by qballer** [GoogleChromeLabs/ndb#82]
I am using (and part of the team developing) a product called [teambit/bit](https://github.com/teambit/bit) and as part of its integration with git there are a lot of javascript files inside the .git folder.  When i open ndb, I get endless amount of parsing errors failing to get source maps from those files (I am developing a typescript project).

Does it make sense to ignore those files? Also, in my use case nothing is accessing those files. So I don't understand why it gives me those errors (I guess its because your try to load them a head of time, just in case)

### Steps to reproduce
Create a sample TS project. 
Create a folder inside .git.
throw some vanilla js files to it.
```ndb ...```

**Tell us about your environment:**
* ndb version: v1.0.14
* Platform / OS version: macOS 10.13.4
* Node.js version: 10.6.0 

**What is the expected result?**
ndb shouldn't spam console with missing source map in case the file isn't required/used in your debugging flow.

**What happens instead?**
Loads of errors for unused files.

**Comment by ak239** [comment]
Just published ndb 1.0.16 should contain fix for this issue.

**Comment by qballer** [comment]
I'm using it and the issue is fixed, works much faster. This is great.
